// AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit by hand.
// Self-hosted registry of ~97 popular Google fonts (vendored via
// @fontsource[-variable], loaded with next/font/local so the BUILD never fetches
// Google Fonts). Every font is offered for BOTH the body and heading, so the two
// admin selects show the SAME list. Each font is declared twice: once for the
// body slot (variable: --font-inter → globals.css maps to --font-sans) and once
// for the heading slot (variable: --font-inter-tight → --font-display, .ns-theme).
// All are declared preload:false: a page applies only the selected body + heading
// font, so only those woff2 files are fetched (not the whole ~97-font registry).
//
// To change the list: edit scripts/fonts-list.json, run `pnpm add` for any new
// packages in apps/{admin,web,widget}, then `node scripts/gen-fonts.mjs`.
// This file is identical across apps/{admin,web,widget}/src/app/fonts.ts.
import localFont from 'next/font/local';

// ============================ Body slot (--font-inter) ============================
const robotoBody = localFont({ src: '../../node_modules/@fontsource-variable/roboto/files/roboto-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const openSansBody = localFont({ src: '../../node_modules/@fontsource-variable/open-sans/files/open-sans-latin-wght-normal.woff2', weight: '300 800', display: 'swap', preload: false, variable: '--font-inter' });
const interBody = localFont({ src: '../../node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const montserratBody = localFont({ src: '../../node_modules/@fontsource-variable/montserrat/files/montserrat-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const poppinsBody = localFont({ src: [{ path: '../../node_modules/@fontsource/poppins/files/poppins-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/poppins/files/poppins-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/poppins/files/poppins-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/poppins/files/poppins-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/poppins/files/poppins-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/poppins/files/poppins-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const latoBody = localFont({ src: [{ path: '../../node_modules/@fontsource/lato/files/lato-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/lato/files/lato-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/lato/files/lato-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const arimoBody = localFont({ src: '../../node_modules/@fontsource-variable/arimo/files/arimo-latin-wght-normal.woff2', weight: '400 700', display: 'swap', preload: false, variable: '--font-inter' });
const robotoCondensedBody = localFont({ src: '../../node_modules/@fontsource-variable/roboto-condensed/files/roboto-condensed-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const robotoMonoBody = localFont({ src: '../../node_modules/@fontsource-variable/roboto-mono/files/roboto-mono-latin-wght-normal.woff2', weight: '100 700', display: 'swap', preload: false, variable: '--font-inter' });
const oswaldBody = localFont({ src: '../../node_modules/@fontsource-variable/oswald/files/oswald-latin-wght-normal.woff2', weight: '200 700', display: 'swap', preload: false, variable: '--font-inter' });
const ralewayBody = localFont({ src: '../../node_modules/@fontsource-variable/raleway/files/raleway-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const nunitoSansBody = localFont({ src: '../../node_modules/@fontsource-variable/nunito-sans/files/nunito-sans-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter' });
const nunitoBody = localFont({ src: '../../node_modules/@fontsource-variable/nunito/files/nunito-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter' });
const dmSansBody = localFont({ src: '../../node_modules/@fontsource-variable/dm-sans/files/dm-sans-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const playfairDisplayBody = localFont({ src: '../../node_modules/@fontsource-variable/playfair-display/files/playfair-display-latin-wght-normal.woff2', weight: '400 900', display: 'swap', preload: false, variable: '--font-inter' });
const robotoSlabBody = localFont({ src: '../../node_modules/@fontsource-variable/roboto-slab/files/roboto-slab-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const rubikBody = localFont({ src: '../../node_modules/@fontsource-variable/rubik/files/rubik-latin-wght-normal.woff2', weight: '300 900', display: 'swap', preload: false, variable: '--font-inter' });
const archivoBlackBody = localFont({ src: [{ path: '../../node_modules/@fontsource/archivo-black/files/archivo-black-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const kanitBody = localFont({ src: [{ path: '../../node_modules/@fontsource/kanit/files/kanit-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/kanit/files/kanit-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/kanit/files/kanit-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/kanit/files/kanit-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/kanit/files/kanit-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/kanit/files/kanit-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const workSansBody = localFont({ src: '../../node_modules/@fontsource-variable/work-sans/files/work-sans-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const outfitBody = localFont({ src: '../../node_modules/@fontsource-variable/outfit/files/outfit-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const manropeBody = localFont({ src: '../../node_modules/@fontsource-variable/manrope/files/manrope-latin-wght-normal.woff2', weight: '200 800', display: 'swap', preload: false, variable: '--font-inter' });
const ptSansBody = localFont({ src: [{ path: '../../node_modules/@fontsource/pt-sans/files/pt-sans-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/pt-sans/files/pt-sans-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const loraBody = localFont({ src: '../../node_modules/@fontsource-variable/lora/files/lora-latin-wght-normal.woff2', weight: '400 700', display: 'swap', preload: false, variable: '--font-inter' });
const mulishBody = localFont({ src: '../../node_modules/@fontsource-variable/mulish/files/mulish-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter' });
const bebasNeueBody = localFont({ src: [{ path: '../../node_modules/@fontsource/bebas-neue/files/bebas-neue-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const inconsolataBody = localFont({ src: '../../node_modules/@fontsource-variable/inconsolata/files/inconsolata-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter' });
const quicksandBody = localFont({ src: '../../node_modules/@fontsource-variable/quicksand/files/quicksand-latin-wght-normal.woff2', weight: '300 700', display: 'swap', preload: false, variable: '--font-inter' });
const promptBody = localFont({ src: [{ path: '../../node_modules/@fontsource/prompt/files/prompt-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/prompt/files/prompt-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/prompt/files/prompt-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/prompt/files/prompt-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/prompt/files/prompt-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/prompt/files/prompt-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const figtreeBody = localFont({ src: '../../node_modules/@fontsource-variable/figtree/files/figtree-latin-wght-normal.woff2', weight: '300 900', display: 'swap', preload: false, variable: '--font-inter' });
const barlowBody = localFont({ src: [{ path: '../../node_modules/@fontsource/barlow/files/barlow-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow/files/barlow-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow/files/barlow-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow/files/barlow-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow/files/barlow-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow/files/barlow-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const sourceSans3Body = localFont({ src: '../../node_modules/@fontsource-variable/source-sans-3/files/source-sans-3-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter' });
const bricolageGrotesqueBody = localFont({ src: '../../node_modules/@fontsource-variable/bricolage-grotesque/files/bricolage-grotesque-latin-wght-normal.woff2', weight: '200 800', display: 'swap', preload: false, variable: '--font-inter' });
const ibmPlexSansBody = localFont({ src: '../../node_modules/@fontsource-variable/ibm-plex-sans/files/ibm-plex-sans-latin-wght-normal.woff2', weight: '100 700', display: 'swap', preload: false, variable: '--font-inter' });
const sairaBody = localFont({ src: '../../node_modules/@fontsource-variable/saira/files/saira-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const plusJakartaSansBody = localFont({ src: '../../node_modules/@fontsource-variable/plus-jakarta-sans/files/plus-jakarta-sans-latin-wght-normal.woff2', weight: '200 800', display: 'swap', preload: false, variable: '--font-inter' });
const firaSansBody = localFont({ src: [{ path: '../../node_modules/@fontsource/fira-sans/files/fira-sans-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/fira-sans/files/fira-sans-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/fira-sans/files/fira-sans-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/fira-sans/files/fira-sans-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/fira-sans/files/fira-sans-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/fira-sans/files/fira-sans-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const titilliumWebBody = localFont({ src: [{ path: '../../node_modules/@fontsource/titillium-web/files/titillium-web-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/titillium-web/files/titillium-web-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/titillium-web/files/titillium-web-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/titillium-web/files/titillium-web-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const karlaBody = localFont({ src: '../../node_modules/@fontsource-variable/karla/files/karla-latin-wght-normal.woff2', weight: '200 800', display: 'swap', preload: false, variable: '--font-inter' });
const jostBody = localFont({ src: '../../node_modules/@fontsource-variable/jost/files/jost-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const blackOpsOneBody = localFont({ src: [{ path: '../../node_modules/@fontsource/black-ops-one/files/black-ops-one-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const shareTechBody = localFont({ src: [{ path: '../../node_modules/@fontsource/share-tech/files/share-tech-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const smoochSansBody = localFont({ src: '../../node_modules/@fontsource-variable/smooch-sans/files/smooch-sans-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const heeboBody = localFont({ src: '../../node_modules/@fontsource-variable/heebo/files/heebo-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const archivoBody = localFont({ src: '../../node_modules/@fontsource-variable/archivo/files/archivo-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const notoSerifBody = localFont({ src: '../../node_modules/@fontsource-variable/noto-serif/files/noto-serif-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const ptSerifBody = localFont({ src: [{ path: '../../node_modules/@fontsource/pt-serif/files/pt-serif-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/pt-serif/files/pt-serif-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const sourceCodeProBody = localFont({ src: '../../node_modules/@fontsource-variable/source-code-pro/files/source-code-pro-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter' });
const dancingScriptBody = localFont({ src: '../../node_modules/@fontsource-variable/dancing-script/files/dancing-script-latin-wght-normal.woff2', weight: '400 700', display: 'swap', preload: false, variable: '--font-inter' });
const libreBaskervilleBody = localFont({ src: '../../node_modules/@fontsource-variable/libre-baskerville/files/libre-baskerville-latin-wght-normal.woff2', weight: '400 700', display: 'swap', preload: false, variable: '--font-inter' });
const fjallaOneBody = localFont({ src: [{ path: '../../node_modules/@fontsource/fjalla-one/files/fjalla-one-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const jetbrainsMonoBody = localFont({ src: '../../node_modules/@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2', weight: '100 800', display: 'swap', preload: false, variable: '--font-inter' });
const lobsterTwoBody = localFont({ src: [{ path: '../../node_modules/@fontsource/lobster-two/files/lobster-two-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/lobster-two/files/lobster-two-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const josefinSansBody = localFont({ src: '../../node_modules/@fontsource-variable/josefin-sans/files/josefin-sans-latin-wght-normal.woff2', weight: '100 700', display: 'swap', preload: false, variable: '--font-inter' });
const libreFranklinBody = localFont({ src: '../../node_modules/@fontsource-variable/libre-franklin/files/libre-franklin-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const antonBody = localFont({ src: [{ path: '../../node_modules/@fontsource/anton/files/anton-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const cormorantGaramondBody = localFont({ src: '../../node_modules/@fontsource-variable/cormorant-garamond/files/cormorant-garamond-latin-wght-normal.woff2', weight: '300 700', display: 'swap', preload: false, variable: '--font-inter' });
const instrumentSerifBody = localFont({ src: [{ path: '../../node_modules/@fontsource/instrument-serif/files/instrument-serif-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const spaceGroteskBody = localFont({ src: '../../node_modules/@fontsource-variable/space-grotesk/files/space-grotesk-latin-wght-normal.woff2', weight: '300 700', display: 'swap', preload: false, variable: '--font-inter' });
const nanumGothicBody = localFont({ src: [{ path: '../../node_modules/@fontsource/nanum-gothic/files/nanum-gothic-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/nanum-gothic/files/nanum-gothic-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/nanum-gothic/files/nanum-gothic-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const barlowCondensedBody = localFont({ src: [{ path: '../../node_modules/@fontsource/barlow-condensed/files/barlow-condensed-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow-condensed/files/barlow-condensed-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow-condensed/files/barlow-condensed-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow-condensed/files/barlow-condensed-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow-condensed/files/barlow-condensed-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow-condensed/files/barlow-condensed-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const publicSansBody = localFont({ src: '../../node_modules/@fontsource-variable/public-sans/files/public-sans-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const changaOneBody = localFont({ src: [{ path: '../../node_modules/@fontsource/changa-one/files/changa-one-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const ebGaramondBody = localFont({ src: '../../node_modules/@fontsource-variable/eb-garamond/files/eb-garamond-latin-wght-normal.woff2', weight: '400 800', display: 'swap', preload: false, variable: '--font-inter' });
const cairoBody = localFont({ src: '../../node_modules/@fontsource-variable/cairo/files/cairo-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter' });
const assistantBody = localFont({ src: '../../node_modules/@fontsource-variable/assistant/files/assistant-latin-wght-normal.woff2', weight: '200 800', display: 'swap', preload: false, variable: '--font-inter' });
const interTightBody = localFont({ src: '../../node_modules/@fontsource-variable/inter-tight/files/inter-tight-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const cabinBody = localFont({ src: '../../node_modules/@fontsource-variable/cabin/files/cabin-latin-wght-normal.woff2', weight: '400 700', display: 'swap', preload: false, variable: '--font-inter' });
const schibstedGroteskBody = localFont({ src: '../../node_modules/@fontsource-variable/schibsted-grotesk/files/schibsted-grotesk-latin-wght-normal.woff2', weight: '400 900', display: 'swap', preload: false, variable: '--font-inter' });
const alfaSlabOneBody = localFont({ src: [{ path: '../../node_modules/@fontsource/alfa-slab-one/files/alfa-slab-one-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const bitterBody = localFont({ src: '../../node_modules/@fontsource-variable/bitter/files/bitter-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const notoSansTeluguBody = localFont({ src: '../../node_modules/@fontsource-variable/noto-sans-telugu/files/noto-sans-telugu-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const ramabhadraBody = localFont({ src: [{ path: '../../node_modules/@fontsource/ramabhadra/files/ramabhadra-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const dosisBody = localFont({ src: '../../node_modules/@fontsource-variable/dosis/files/dosis-latin-wght-normal.woff2', weight: '200 800', display: 'swap', preload: false, variable: '--font-inter' });
const robotoFlexBody = localFont({ src: '../../node_modules/@fontsource-variable/roboto-flex/files/roboto-flex-latin-wght-normal.woff2', weight: '400', display: 'swap', preload: false, variable: '--font-inter' });
const anekTeluguBody = localFont({ src: '../../node_modules/@fontsource-variable/anek-telugu/files/anek-telugu-latin-wght-normal.woff2', weight: '100 800', display: 'swap', preload: false, variable: '--font-inter' });
const soraBody = localFont({ src: '../../node_modules/@fontsource-variable/sora/files/sora-latin-wght-normal.woff2', weight: '100 800', display: 'swap', preload: false, variable: '--font-inter' });
const notoSansKhmerBody = localFont({ src: '../../node_modules/@fontsource-variable/noto-sans-khmer/files/noto-sans-khmer-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const mPlusRounded1cBody = localFont({ src: [{ path: '../../node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const redHatDisplayBody = localFont({ src: '../../node_modules/@fontsource-variable/red-hat-display/files/red-hat-display-latin-wght-normal.woff2', weight: '300 900', display: 'swap', preload: false, variable: '--font-inter' });
const overpassBody = localFont({ src: '../../node_modules/@fontsource-variable/overpass/files/overpass-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const lexendBody = localFont({ src: '../../node_modules/@fontsource-variable/lexend/files/lexend-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const fredokaBody = localFont({ src: '../../node_modules/@fontsource-variable/fredoka/files/fredoka-latin-wght-normal.woff2', weight: '300 700', display: 'swap', preload: false, variable: '--font-inter' });
const rajdhaniBody = localFont({ src: [{ path: '../../node_modules/@fontsource/rajdhani/files/rajdhani-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/rajdhani/files/rajdhani-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/rajdhani/files/rajdhani-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/rajdhani/files/rajdhani-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/rajdhani/files/rajdhani-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const hindSiliguriBody = localFont({ src: [{ path: '../../node_modules/@fontsource/hind-siliguri/files/hind-siliguri-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/hind-siliguri/files/hind-siliguri-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/hind-siliguri/files/hind-siliguri-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/hind-siliguri/files/hind-siliguri-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/hind-siliguri/files/hind-siliguri-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const exo2Body = localFont({ src: '../../node_modules/@fontsource-variable/exo-2/files/exo-2-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const oxygenBody = localFont({ src: [{ path: '../../node_modules/@fontsource/oxygen/files/oxygen-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/oxygen/files/oxygen-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/oxygen/files/oxygen-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const caveatBody = localFont({ src: '../../node_modules/@fontsource-variable/caveat/files/caveat-latin-wght-normal.woff2', weight: '400 700', display: 'swap', preload: false, variable: '--font-inter' });
const muktaBody = localFont({ src: [{ path: '../../node_modules/@fontsource/mukta/files/mukta-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/mukta/files/mukta-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/mukta/files/mukta-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/mukta/files/mukta-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/mukta/files/mukta-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/mukta/files/mukta-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const urbanistBody = localFont({ src: '../../node_modules/@fontsource-variable/urbanist/files/urbanist-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter' });
const hindBody = localFont({ src: [{ path: '../../node_modules/@fontsource/hind/files/hind-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/hind/files/hind-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/hind/files/hind-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/hind/files/hind-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/hind/files/hind-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const crimsonTextBody = localFont({ src: [{ path: '../../node_modules/@fontsource/crimson-text/files/crimson-text-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/crimson-text/files/crimson-text-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/crimson-text/files/crimson-text-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const lilitaOneBody = localFont({ src: [{ path: '../../node_modules/@fontsource/lilita-one/files/lilita-one-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const bungeeBody = localFont({ src: [{ path: '../../node_modules/@fontsource/bungee/files/bungee-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const pacificoBody = localFont({ src: [{ path: '../../node_modules/@fontsource/pacifico/files/pacifico-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const dmSerifDisplayBody = localFont({ src: [{ path: '../../node_modules/@fontsource/dm-serif-display/files/dm-serif-display-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter' });
const orbitronBody = localFont({ src: '../../node_modules/@fontsource-variable/orbitron/files/orbitron-latin-wght-normal.woff2', weight: '400 900', display: 'swap', preload: false, variable: '--font-inter' });

// ========================== Heading slot (--font-inter-tight) ==========================
const robotoHead = localFont({ src: '../../node_modules/@fontsource-variable/roboto/files/roboto-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const openSansHead = localFont({ src: '../../node_modules/@fontsource-variable/open-sans/files/open-sans-latin-wght-normal.woff2', weight: '300 800', display: 'swap', preload: false, variable: '--font-inter-tight' });
const interHead = localFont({ src: '../../node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const montserratHead = localFont({ src: '../../node_modules/@fontsource-variable/montserrat/files/montserrat-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const poppinsHead = localFont({ src: [{ path: '../../node_modules/@fontsource/poppins/files/poppins-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/poppins/files/poppins-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/poppins/files/poppins-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/poppins/files/poppins-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/poppins/files/poppins-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/poppins/files/poppins-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const latoHead = localFont({ src: [{ path: '../../node_modules/@fontsource/lato/files/lato-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/lato/files/lato-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/lato/files/lato-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const arimoHead = localFont({ src: '../../node_modules/@fontsource-variable/arimo/files/arimo-latin-wght-normal.woff2', weight: '400 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const robotoCondensedHead = localFont({ src: '../../node_modules/@fontsource-variable/roboto-condensed/files/roboto-condensed-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const robotoMonoHead = localFont({ src: '../../node_modules/@fontsource-variable/roboto-mono/files/roboto-mono-latin-wght-normal.woff2', weight: '100 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const oswaldHead = localFont({ src: '../../node_modules/@fontsource-variable/oswald/files/oswald-latin-wght-normal.woff2', weight: '200 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const ralewayHead = localFont({ src: '../../node_modules/@fontsource-variable/raleway/files/raleway-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const nunitoSansHead = localFont({ src: '../../node_modules/@fontsource-variable/nunito-sans/files/nunito-sans-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const nunitoHead = localFont({ src: '../../node_modules/@fontsource-variable/nunito/files/nunito-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const dmSansHead = localFont({ src: '../../node_modules/@fontsource-variable/dm-sans/files/dm-sans-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const playfairDisplayHead = localFont({ src: '../../node_modules/@fontsource-variable/playfair-display/files/playfair-display-latin-wght-normal.woff2', weight: '400 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const robotoSlabHead = localFont({ src: '../../node_modules/@fontsource-variable/roboto-slab/files/roboto-slab-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const rubikHead = localFont({ src: '../../node_modules/@fontsource-variable/rubik/files/rubik-latin-wght-normal.woff2', weight: '300 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const archivoBlackHead = localFont({ src: [{ path: '../../node_modules/@fontsource/archivo-black/files/archivo-black-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const kanitHead = localFont({ src: [{ path: '../../node_modules/@fontsource/kanit/files/kanit-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/kanit/files/kanit-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/kanit/files/kanit-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/kanit/files/kanit-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/kanit/files/kanit-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/kanit/files/kanit-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const workSansHead = localFont({ src: '../../node_modules/@fontsource-variable/work-sans/files/work-sans-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const outfitHead = localFont({ src: '../../node_modules/@fontsource-variable/outfit/files/outfit-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const manropeHead = localFont({ src: '../../node_modules/@fontsource-variable/manrope/files/manrope-latin-wght-normal.woff2', weight: '200 800', display: 'swap', preload: false, variable: '--font-inter-tight' });
const ptSansHead = localFont({ src: [{ path: '../../node_modules/@fontsource/pt-sans/files/pt-sans-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/pt-sans/files/pt-sans-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const loraHead = localFont({ src: '../../node_modules/@fontsource-variable/lora/files/lora-latin-wght-normal.woff2', weight: '400 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const mulishHead = localFont({ src: '../../node_modules/@fontsource-variable/mulish/files/mulish-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const bebasNeueHead = localFont({ src: [{ path: '../../node_modules/@fontsource/bebas-neue/files/bebas-neue-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const inconsolataHead = localFont({ src: '../../node_modules/@fontsource-variable/inconsolata/files/inconsolata-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const quicksandHead = localFont({ src: '../../node_modules/@fontsource-variable/quicksand/files/quicksand-latin-wght-normal.woff2', weight: '300 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const promptHead = localFont({ src: [{ path: '../../node_modules/@fontsource/prompt/files/prompt-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/prompt/files/prompt-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/prompt/files/prompt-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/prompt/files/prompt-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/prompt/files/prompt-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/prompt/files/prompt-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const figtreeHead = localFont({ src: '../../node_modules/@fontsource-variable/figtree/files/figtree-latin-wght-normal.woff2', weight: '300 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const barlowHead = localFont({ src: [{ path: '../../node_modules/@fontsource/barlow/files/barlow-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow/files/barlow-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow/files/barlow-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow/files/barlow-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow/files/barlow-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow/files/barlow-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const sourceSans3Head = localFont({ src: '../../node_modules/@fontsource-variable/source-sans-3/files/source-sans-3-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const bricolageGrotesqueHead = localFont({ src: '../../node_modules/@fontsource-variable/bricolage-grotesque/files/bricolage-grotesque-latin-wght-normal.woff2', weight: '200 800', display: 'swap', preload: false, variable: '--font-inter-tight' });
const ibmPlexSansHead = localFont({ src: '../../node_modules/@fontsource-variable/ibm-plex-sans/files/ibm-plex-sans-latin-wght-normal.woff2', weight: '100 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const sairaHead = localFont({ src: '../../node_modules/@fontsource-variable/saira/files/saira-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const plusJakartaSansHead = localFont({ src: '../../node_modules/@fontsource-variable/plus-jakarta-sans/files/plus-jakarta-sans-latin-wght-normal.woff2', weight: '200 800', display: 'swap', preload: false, variable: '--font-inter-tight' });
const firaSansHead = localFont({ src: [{ path: '../../node_modules/@fontsource/fira-sans/files/fira-sans-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/fira-sans/files/fira-sans-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/fira-sans/files/fira-sans-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/fira-sans/files/fira-sans-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/fira-sans/files/fira-sans-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/fira-sans/files/fira-sans-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const titilliumWebHead = localFont({ src: [{ path: '../../node_modules/@fontsource/titillium-web/files/titillium-web-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/titillium-web/files/titillium-web-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/titillium-web/files/titillium-web-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/titillium-web/files/titillium-web-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const karlaHead = localFont({ src: '../../node_modules/@fontsource-variable/karla/files/karla-latin-wght-normal.woff2', weight: '200 800', display: 'swap', preload: false, variable: '--font-inter-tight' });
const jostHead = localFont({ src: '../../node_modules/@fontsource-variable/jost/files/jost-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const blackOpsOneHead = localFont({ src: [{ path: '../../node_modules/@fontsource/black-ops-one/files/black-ops-one-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const shareTechHead = localFont({ src: [{ path: '../../node_modules/@fontsource/share-tech/files/share-tech-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const smoochSansHead = localFont({ src: '../../node_modules/@fontsource-variable/smooch-sans/files/smooch-sans-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const heeboHead = localFont({ src: '../../node_modules/@fontsource-variable/heebo/files/heebo-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const archivoHead = localFont({ src: '../../node_modules/@fontsource-variable/archivo/files/archivo-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const notoSerifHead = localFont({ src: '../../node_modules/@fontsource-variable/noto-serif/files/noto-serif-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const ptSerifHead = localFont({ src: [{ path: '../../node_modules/@fontsource/pt-serif/files/pt-serif-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/pt-serif/files/pt-serif-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const sourceCodeProHead = localFont({ src: '../../node_modules/@fontsource-variable/source-code-pro/files/source-code-pro-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const dancingScriptHead = localFont({ src: '../../node_modules/@fontsource-variable/dancing-script/files/dancing-script-latin-wght-normal.woff2', weight: '400 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const libreBaskervilleHead = localFont({ src: '../../node_modules/@fontsource-variable/libre-baskerville/files/libre-baskerville-latin-wght-normal.woff2', weight: '400 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const fjallaOneHead = localFont({ src: [{ path: '../../node_modules/@fontsource/fjalla-one/files/fjalla-one-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const jetbrainsMonoHead = localFont({ src: '../../node_modules/@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2', weight: '100 800', display: 'swap', preload: false, variable: '--font-inter-tight' });
const lobsterTwoHead = localFont({ src: [{ path: '../../node_modules/@fontsource/lobster-two/files/lobster-two-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/lobster-two/files/lobster-two-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const josefinSansHead = localFont({ src: '../../node_modules/@fontsource-variable/josefin-sans/files/josefin-sans-latin-wght-normal.woff2', weight: '100 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const libreFranklinHead = localFont({ src: '../../node_modules/@fontsource-variable/libre-franklin/files/libre-franklin-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const antonHead = localFont({ src: [{ path: '../../node_modules/@fontsource/anton/files/anton-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const cormorantGaramondHead = localFont({ src: '../../node_modules/@fontsource-variable/cormorant-garamond/files/cormorant-garamond-latin-wght-normal.woff2', weight: '300 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const instrumentSerifHead = localFont({ src: [{ path: '../../node_modules/@fontsource/instrument-serif/files/instrument-serif-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const spaceGroteskHead = localFont({ src: '../../node_modules/@fontsource-variable/space-grotesk/files/space-grotesk-latin-wght-normal.woff2', weight: '300 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const nanumGothicHead = localFont({ src: [{ path: '../../node_modules/@fontsource/nanum-gothic/files/nanum-gothic-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/nanum-gothic/files/nanum-gothic-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/nanum-gothic/files/nanum-gothic-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const barlowCondensedHead = localFont({ src: [{ path: '../../node_modules/@fontsource/barlow-condensed/files/barlow-condensed-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow-condensed/files/barlow-condensed-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow-condensed/files/barlow-condensed-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow-condensed/files/barlow-condensed-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow-condensed/files/barlow-condensed-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/barlow-condensed/files/barlow-condensed-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const publicSansHead = localFont({ src: '../../node_modules/@fontsource-variable/public-sans/files/public-sans-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const changaOneHead = localFont({ src: [{ path: '../../node_modules/@fontsource/changa-one/files/changa-one-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const ebGaramondHead = localFont({ src: '../../node_modules/@fontsource-variable/eb-garamond/files/eb-garamond-latin-wght-normal.woff2', weight: '400 800', display: 'swap', preload: false, variable: '--font-inter-tight' });
const cairoHead = localFont({ src: '../../node_modules/@fontsource-variable/cairo/files/cairo-latin-wght-normal.woff2', weight: '200 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const assistantHead = localFont({ src: '../../node_modules/@fontsource-variable/assistant/files/assistant-latin-wght-normal.woff2', weight: '200 800', display: 'swap', preload: false, variable: '--font-inter-tight' });
const interTightHead = localFont({ src: '../../node_modules/@fontsource-variable/inter-tight/files/inter-tight-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const cabinHead = localFont({ src: '../../node_modules/@fontsource-variable/cabin/files/cabin-latin-wght-normal.woff2', weight: '400 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const schibstedGroteskHead = localFont({ src: '../../node_modules/@fontsource-variable/schibsted-grotesk/files/schibsted-grotesk-latin-wght-normal.woff2', weight: '400 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const alfaSlabOneHead = localFont({ src: [{ path: '../../node_modules/@fontsource/alfa-slab-one/files/alfa-slab-one-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const bitterHead = localFont({ src: '../../node_modules/@fontsource-variable/bitter/files/bitter-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const notoSansTeluguHead = localFont({ src: '../../node_modules/@fontsource-variable/noto-sans-telugu/files/noto-sans-telugu-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const ramabhadraHead = localFont({ src: [{ path: '../../node_modules/@fontsource/ramabhadra/files/ramabhadra-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const dosisHead = localFont({ src: '../../node_modules/@fontsource-variable/dosis/files/dosis-latin-wght-normal.woff2', weight: '200 800', display: 'swap', preload: false, variable: '--font-inter-tight' });
const robotoFlexHead = localFont({ src: '../../node_modules/@fontsource-variable/roboto-flex/files/roboto-flex-latin-wght-normal.woff2', weight: '400', display: 'swap', preload: false, variable: '--font-inter-tight' });
const anekTeluguHead = localFont({ src: '../../node_modules/@fontsource-variable/anek-telugu/files/anek-telugu-latin-wght-normal.woff2', weight: '100 800', display: 'swap', preload: false, variable: '--font-inter-tight' });
const soraHead = localFont({ src: '../../node_modules/@fontsource-variable/sora/files/sora-latin-wght-normal.woff2', weight: '100 800', display: 'swap', preload: false, variable: '--font-inter-tight' });
const notoSansKhmerHead = localFont({ src: '../../node_modules/@fontsource-variable/noto-sans-khmer/files/noto-sans-khmer-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const mPlusRounded1cHead = localFont({ src: [{ path: '../../node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const redHatDisplayHead = localFont({ src: '../../node_modules/@fontsource-variable/red-hat-display/files/red-hat-display-latin-wght-normal.woff2', weight: '300 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const overpassHead = localFont({ src: '../../node_modules/@fontsource-variable/overpass/files/overpass-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const lexendHead = localFont({ src: '../../node_modules/@fontsource-variable/lexend/files/lexend-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const fredokaHead = localFont({ src: '../../node_modules/@fontsource-variable/fredoka/files/fredoka-latin-wght-normal.woff2', weight: '300 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const rajdhaniHead = localFont({ src: [{ path: '../../node_modules/@fontsource/rajdhani/files/rajdhani-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/rajdhani/files/rajdhani-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/rajdhani/files/rajdhani-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/rajdhani/files/rajdhani-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/rajdhani/files/rajdhani-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const hindSiliguriHead = localFont({ src: [{ path: '../../node_modules/@fontsource/hind-siliguri/files/hind-siliguri-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/hind-siliguri/files/hind-siliguri-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/hind-siliguri/files/hind-siliguri-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/hind-siliguri/files/hind-siliguri-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/hind-siliguri/files/hind-siliguri-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const exo2Head = localFont({ src: '../../node_modules/@fontsource-variable/exo-2/files/exo-2-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const oxygenHead = localFont({ src: [{ path: '../../node_modules/@fontsource/oxygen/files/oxygen-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/oxygen/files/oxygen-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/oxygen/files/oxygen-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const caveatHead = localFont({ src: '../../node_modules/@fontsource-variable/caveat/files/caveat-latin-wght-normal.woff2', weight: '400 700', display: 'swap', preload: false, variable: '--font-inter-tight' });
const muktaHead = localFont({ src: [{ path: '../../node_modules/@fontsource/mukta/files/mukta-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/mukta/files/mukta-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/mukta/files/mukta-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/mukta/files/mukta-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/mukta/files/mukta-latin-700-normal.woff2', weight: '700', style: 'normal' }, { path: '../../node_modules/@fontsource/mukta/files/mukta-latin-800-normal.woff2', weight: '800', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const urbanistHead = localFont({ src: '../../node_modules/@fontsource-variable/urbanist/files/urbanist-latin-wght-normal.woff2', weight: '100 900', display: 'swap', preload: false, variable: '--font-inter-tight' });
const hindHead = localFont({ src: [{ path: '../../node_modules/@fontsource/hind/files/hind-latin-300-normal.woff2', weight: '300', style: 'normal' }, { path: '../../node_modules/@fontsource/hind/files/hind-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/hind/files/hind-latin-500-normal.woff2', weight: '500', style: 'normal' }, { path: '../../node_modules/@fontsource/hind/files/hind-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/hind/files/hind-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const crimsonTextHead = localFont({ src: [{ path: '../../node_modules/@fontsource/crimson-text/files/crimson-text-latin-400-normal.woff2', weight: '400', style: 'normal' }, { path: '../../node_modules/@fontsource/crimson-text/files/crimson-text-latin-600-normal.woff2', weight: '600', style: 'normal' }, { path: '../../node_modules/@fontsource/crimson-text/files/crimson-text-latin-700-normal.woff2', weight: '700', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const lilitaOneHead = localFont({ src: [{ path: '../../node_modules/@fontsource/lilita-one/files/lilita-one-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const bungeeHead = localFont({ src: [{ path: '../../node_modules/@fontsource/bungee/files/bungee-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const pacificoHead = localFont({ src: [{ path: '../../node_modules/@fontsource/pacifico/files/pacifico-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const dmSerifDisplayHead = localFont({ src: [{ path: '../../node_modules/@fontsource/dm-serif-display/files/dm-serif-display-latin-400-normal.woff2', weight: '400', style: 'normal' }], display: 'swap', preload: false, variable: '--font-inter-tight' });
const orbitronHead = localFont({ src: '../../node_modules/@fontsource-variable/orbitron/files/orbitron-latin-wght-normal.woff2', weight: '400 900', display: 'swap', preload: false, variable: '--font-inter-tight' });

// Same keys in both maps → the body and heading selects offer the same fonts.
export const SANS_FONTS = {
  "roboto": robotoBody,
  "open-sans": openSansBody,
  "inter": interBody,
  "montserrat": montserratBody,
  "poppins": poppinsBody,
  "lato": latoBody,
  "arimo": arimoBody,
  "roboto-condensed": robotoCondensedBody,
  "roboto-mono": robotoMonoBody,
  "oswald": oswaldBody,
  "raleway": ralewayBody,
  "nunito-sans": nunitoSansBody,
  "nunito": nunitoBody,
  "dm-sans": dmSansBody,
  "playfair-display": playfairDisplayBody,
  "roboto-slab": robotoSlabBody,
  "rubik": rubikBody,
  "archivo-black": archivoBlackBody,
  "kanit": kanitBody,
  "work-sans": workSansBody,
  "outfit": outfitBody,
  "manrope": manropeBody,
  "pt-sans": ptSansBody,
  "lora": loraBody,
  "mulish": mulishBody,
  "bebas-neue": bebasNeueBody,
  "inconsolata": inconsolataBody,
  "quicksand": quicksandBody,
  "prompt": promptBody,
  "figtree": figtreeBody,
  "barlow": barlowBody,
  "source-sans-3": sourceSans3Body,
  "bricolage-grotesque": bricolageGrotesqueBody,
  "ibm-plex-sans": ibmPlexSansBody,
  "saira": sairaBody,
  "plus-jakarta-sans": plusJakartaSansBody,
  "fira-sans": firaSansBody,
  "titillium-web": titilliumWebBody,
  "karla": karlaBody,
  "jost": jostBody,
  "black-ops-one": blackOpsOneBody,
  "share-tech": shareTechBody,
  "smooch-sans": smoochSansBody,
  "heebo": heeboBody,
  "archivo": archivoBody,
  "noto-serif": notoSerifBody,
  "pt-serif": ptSerifBody,
  "source-code-pro": sourceCodeProBody,
  "dancing-script": dancingScriptBody,
  "libre-baskerville": libreBaskervilleBody,
  "fjalla-one": fjallaOneBody,
  "jetbrains-mono": jetbrainsMonoBody,
  "lobster-two": lobsterTwoBody,
  "josefin-sans": josefinSansBody,
  "libre-franklin": libreFranklinBody,
  "anton": antonBody,
  "cormorant-garamond": cormorantGaramondBody,
  "instrument-serif": instrumentSerifBody,
  "space-grotesk": spaceGroteskBody,
  "nanum-gothic": nanumGothicBody,
  "barlow-condensed": barlowCondensedBody,
  "public-sans": publicSansBody,
  "changa-one": changaOneBody,
  "eb-garamond": ebGaramondBody,
  "cairo": cairoBody,
  "assistant": assistantBody,
  "inter-tight": interTightBody,
  "cabin": cabinBody,
  "schibsted-grotesk": schibstedGroteskBody,
  "alfa-slab-one": alfaSlabOneBody,
  "bitter": bitterBody,
  "noto-sans-telugu": notoSansTeluguBody,
  "ramabhadra": ramabhadraBody,
  "dosis": dosisBody,
  "roboto-flex": robotoFlexBody,
  "anek-telugu": anekTeluguBody,
  "sora": soraBody,
  "noto-sans-khmer": notoSansKhmerBody,
  "m-plus-rounded-1c": mPlusRounded1cBody,
  "red-hat-display": redHatDisplayBody,
  "overpass": overpassBody,
  "lexend": lexendBody,
  "fredoka": fredokaBody,
  "rajdhani": rajdhaniBody,
  "hind-siliguri": hindSiliguriBody,
  "exo-2": exo2Body,
  "oxygen": oxygenBody,
  "caveat": caveatBody,
  "mukta": muktaBody,
  "urbanist": urbanistBody,
  "hind": hindBody,
  "crimson-text": crimsonTextBody,
  "lilita-one": lilitaOneBody,
  "bungee": bungeeBody,
  "pacifico": pacificoBody,
  "dm-serif-display": dmSerifDisplayBody,
  "orbitron": orbitronBody,
} as const;

export const DISPLAY_FONTS = {
  "roboto": robotoHead,
  "open-sans": openSansHead,
  "inter": interHead,
  "montserrat": montserratHead,
  "poppins": poppinsHead,
  "lato": latoHead,
  "arimo": arimoHead,
  "roboto-condensed": robotoCondensedHead,
  "roboto-mono": robotoMonoHead,
  "oswald": oswaldHead,
  "raleway": ralewayHead,
  "nunito-sans": nunitoSansHead,
  "nunito": nunitoHead,
  "dm-sans": dmSansHead,
  "playfair-display": playfairDisplayHead,
  "roboto-slab": robotoSlabHead,
  "rubik": rubikHead,
  "archivo-black": archivoBlackHead,
  "kanit": kanitHead,
  "work-sans": workSansHead,
  "outfit": outfitHead,
  "manrope": manropeHead,
  "pt-sans": ptSansHead,
  "lora": loraHead,
  "mulish": mulishHead,
  "bebas-neue": bebasNeueHead,
  "inconsolata": inconsolataHead,
  "quicksand": quicksandHead,
  "prompt": promptHead,
  "figtree": figtreeHead,
  "barlow": barlowHead,
  "source-sans-3": sourceSans3Head,
  "bricolage-grotesque": bricolageGrotesqueHead,
  "ibm-plex-sans": ibmPlexSansHead,
  "saira": sairaHead,
  "plus-jakarta-sans": plusJakartaSansHead,
  "fira-sans": firaSansHead,
  "titillium-web": titilliumWebHead,
  "karla": karlaHead,
  "jost": jostHead,
  "black-ops-one": blackOpsOneHead,
  "share-tech": shareTechHead,
  "smooch-sans": smoochSansHead,
  "heebo": heeboHead,
  "archivo": archivoHead,
  "noto-serif": notoSerifHead,
  "pt-serif": ptSerifHead,
  "source-code-pro": sourceCodeProHead,
  "dancing-script": dancingScriptHead,
  "libre-baskerville": libreBaskervilleHead,
  "fjalla-one": fjallaOneHead,
  "jetbrains-mono": jetbrainsMonoHead,
  "lobster-two": lobsterTwoHead,
  "josefin-sans": josefinSansHead,
  "libre-franklin": libreFranklinHead,
  "anton": antonHead,
  "cormorant-garamond": cormorantGaramondHead,
  "instrument-serif": instrumentSerifHead,
  "space-grotesk": spaceGroteskHead,
  "nanum-gothic": nanumGothicHead,
  "barlow-condensed": barlowCondensedHead,
  "public-sans": publicSansHead,
  "changa-one": changaOneHead,
  "eb-garamond": ebGaramondHead,
  "cairo": cairoHead,
  "assistant": assistantHead,
  "inter-tight": interTightHead,
  "cabin": cabinHead,
  "schibsted-grotesk": schibstedGroteskHead,
  "alfa-slab-one": alfaSlabOneHead,
  "bitter": bitterHead,
  "noto-sans-telugu": notoSansTeluguHead,
  "ramabhadra": ramabhadraHead,
  "dosis": dosisHead,
  "roboto-flex": robotoFlexHead,
  "anek-telugu": anekTeluguHead,
  "sora": soraHead,
  "noto-sans-khmer": notoSansKhmerHead,
  "m-plus-rounded-1c": mPlusRounded1cHead,
  "red-hat-display": redHatDisplayHead,
  "overpass": overpassHead,
  "lexend": lexendHead,
  "fredoka": fredokaHead,
  "rajdhani": rajdhaniHead,
  "hind-siliguri": hindSiliguriHead,
  "exo-2": exo2Head,
  "oxygen": oxygenHead,
  "caveat": caveatHead,
  "mukta": muktaHead,
  "urbanist": urbanistHead,
  "hind": hindHead,
  "crimson-text": crimsonTextHead,
  "lilita-one": lilitaOneHead,
  "bungee": bungeeHead,
  "pacifico": pacificoHead,
  "dm-serif-display": dmSerifDisplayHead,
  "orbitron": orbitronHead,
} as const;

export type SansKey = keyof typeof SANS_FONTS;
export type DisplayKey = keyof typeof DISPLAY_FONTS;

export const DEFAULT_SANS: SansKey = 'inter';
export const DEFAULT_DISPLAY: DisplayKey = 'inter-tight';

export function sansFont(key?: string | null) {
  return SANS_FONTS[(key as SansKey)] ?? SANS_FONTS[DEFAULT_SANS];
}
export function displayFont(key?: string | null) {
  return DISPLAY_FONTS[(key as DisplayKey)] ?? DISPLAY_FONTS[DEFAULT_DISPLAY];
}

// Body and heading offer the SAME options (popular Google fonts). Category is
// noted in the label so serif/mono/display/handwriting fonts are recognisable.
export const FONT_OPTIONS: { value: SansKey; label: string }[] = [
  { value: "roboto", label: "Roboto" },
  { value: "open-sans", label: "Open Sans" },
  { value: "inter", label: "Inter" },
  { value: "montserrat", label: "Montserrat" },
  { value: "poppins", label: "Poppins" },
  { value: "lato", label: "Lato" },
  { value: "arimo", label: "Arimo" },
  { value: "roboto-condensed", label: "Roboto Condensed" },
  { value: "roboto-mono", label: "Roboto Mono (mono)" },
  { value: "oswald", label: "Oswald" },
  { value: "raleway", label: "Raleway" },
  { value: "nunito-sans", label: "Nunito Sans" },
  { value: "nunito", label: "Nunito" },
  { value: "dm-sans", label: "DM Sans" },
  { value: "playfair-display", label: "Playfair Display (serif)" },
  { value: "roboto-slab", label: "Roboto Slab (serif)" },
  { value: "rubik", label: "Rubik" },
  { value: "archivo-black", label: "Archivo Black" },
  { value: "kanit", label: "Kanit" },
  { value: "work-sans", label: "Work Sans" },
  { value: "outfit", label: "Outfit" },
  { value: "manrope", label: "Manrope" },
  { value: "pt-sans", label: "PT Sans" },
  { value: "lora", label: "Lora (serif)" },
  { value: "mulish", label: "Mulish" },
  { value: "bebas-neue", label: "Bebas Neue" },
  { value: "inconsolata", label: "Inconsolata (mono)" },
  { value: "quicksand", label: "Quicksand" },
  { value: "prompt", label: "Prompt" },
  { value: "figtree", label: "Figtree" },
  { value: "barlow", label: "Barlow" },
  { value: "source-sans-3", label: "Source Sans 3" },
  { value: "bricolage-grotesque", label: "Bricolage Grotesque" },
  { value: "ibm-plex-sans", label: "IBM Plex Sans" },
  { value: "saira", label: "Saira" },
  { value: "plus-jakarta-sans", label: "Plus Jakarta Sans" },
  { value: "fira-sans", label: "Fira Sans" },
  { value: "titillium-web", label: "Titillium Web" },
  { value: "karla", label: "Karla" },
  { value: "jost", label: "Jost" },
  { value: "black-ops-one", label: "Black Ops One (display)" },
  { value: "share-tech", label: "Share Tech" },
  { value: "smooch-sans", label: "Smooch Sans" },
  { value: "heebo", label: "Heebo" },
  { value: "archivo", label: "Archivo" },
  { value: "noto-serif", label: "Noto Serif (serif)" },
  { value: "pt-serif", label: "PT Serif (serif)" },
  { value: "source-code-pro", label: "Source Code Pro (mono)" },
  { value: "dancing-script", label: "Dancing Script (handwriting)" },
  { value: "libre-baskerville", label: "Libre Baskerville (serif)" },
  { value: "fjalla-one", label: "Fjalla One" },
  { value: "jetbrains-mono", label: "JetBrains Mono (mono)" },
  { value: "lobster-two", label: "Lobster Two (display)" },
  { value: "josefin-sans", label: "Josefin Sans" },
  { value: "libre-franklin", label: "Libre Franklin" },
  { value: "anton", label: "Anton" },
  { value: "cormorant-garamond", label: "Cormorant Garamond (serif)" },
  { value: "instrument-serif", label: "Instrument Serif (serif)" },
  { value: "space-grotesk", label: "Space Grotesk" },
  { value: "nanum-gothic", label: "Nanum Gothic" },
  { value: "barlow-condensed", label: "Barlow Condensed" },
  { value: "public-sans", label: "Public Sans" },
  { value: "changa-one", label: "Changa One (display)" },
  { value: "eb-garamond", label: "EB Garamond (serif)" },
  { value: "cairo", label: "Cairo" },
  { value: "assistant", label: "Assistant" },
  { value: "inter-tight", label: "Inter Tight" },
  { value: "cabin", label: "Cabin" },
  { value: "schibsted-grotesk", label: "Schibsted Grotesk" },
  { value: "alfa-slab-one", label: "Alfa Slab One (display)" },
  { value: "bitter", label: "Bitter (serif)" },
  { value: "noto-sans-telugu", label: "Noto Sans Telugu" },
  { value: "ramabhadra", label: "Ramabhadra" },
  { value: "dosis", label: "Dosis" },
  { value: "roboto-flex", label: "Roboto Flex" },
  { value: "anek-telugu", label: "Anek Telugu" },
  { value: "sora", label: "Sora" },
  { value: "noto-sans-khmer", label: "Noto Sans Khmer" },
  { value: "m-plus-rounded-1c", label: "M PLUS Rounded 1c" },
  { value: "red-hat-display", label: "Red Hat Display" },
  { value: "overpass", label: "Overpass" },
  { value: "lexend", label: "Lexend" },
  { value: "fredoka", label: "Fredoka" },
  { value: "rajdhani", label: "Rajdhani" },
  { value: "hind-siliguri", label: "Hind Siliguri" },
  { value: "exo-2", label: "Exo 2" },
  { value: "oxygen", label: "Oxygen" },
  { value: "caveat", label: "Caveat (handwriting)" },
  { value: "mukta", label: "Mukta" },
  { value: "urbanist", label: "Urbanist" },
  { value: "hind", label: "Hind" },
  { value: "crimson-text", label: "Crimson Text (serif)" },
  { value: "lilita-one", label: "Lilita One (display)" },
  { value: "bungee", label: "Bungee (display)" },
  { value: "pacifico", label: "Pacifico (handwriting)" },
  { value: "dm-serif-display", label: "DM Serif Display (serif)" },
  { value: "orbitron", label: "Orbitron" },
];
export const SANS_OPTIONS = FONT_OPTIONS;
export const DISPLAY_OPTIONS: { value: DisplayKey; label: string }[] = FONT_OPTIONS;
