server {
  listen 80 default_server;
  server_name _;
  root /usr/share/nginx/html;

  location = /widget.js {
    add_header Cache-Control "public, max-age=300, s-maxage=86400, stale-while-revalidate=86400";
    add_header Access-Control-Allow-Origin "*";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
