// Generates the self-hosted font registry shared by apps/{admin,web,widget}.
//
// Reads scripts/fonts-list.json (curated ~100 popular Google fonts), scans the
// installed @fontsource[-variable] packages for the right woff2 files, and writes
// an identical fonts.ts into each app plus the API's font-keys list. next/font/local
// needs STRING LITERAL src paths, so we emit literals.
//
// Regenerate after editing the list / installing fonts:
//   node scripts/gen-fonts.mjs
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const LIST = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts/fonts-list.json'), 'utf8'));
// Paths inside files/ are identical across apps (same packages); scan admin's.
const SCAN_APP = 'apps/admin';
const STATIC_WEIGHTS = [300, 400, 500, 600, 700, 800];

const camel = (s) =>
  s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()).replace(/^[0-9]/, (d) => 'f' + d);

const CAT_SUFFIX = {
  serif: ' (serif)',
  monospace: ' (mono)',
  handwriting: ' (handwriting)',
  display: ' (display)',
};

function resolveFont(font) {
  const pkg = font.variable ? `@fontsource-variable/${font.slug}` : `@fontsource/${font.slug}`;
  const dir = path.join(ROOT, SCAN_APP, 'node_modules', pkg, 'files');
  if (!fs.existsSync(dir)) throw new Error(`missing package files: ${pkg}`);
  const files = fs.readdirSync(dir);
  if (font.variable) {
    const prefer = [
      `${font.slug}-latin-wght-normal.woff2`,
      `${font.slug}-latin-standard-normal.woff2`,
      `${font.slug}-latin-opsz-normal.woff2`,
      `${font.slug}-latin-full-normal.woff2`,
    ];
    const file =
      prefer.find((f) => files.includes(f)) ||
      files.find((f) => /-latin-.*-normal\.woff2$/.test(f) && !f.includes('italic'));
    if (!file) throw new Error(`no latin woff2 for ${pkg}`);
    const ws = font.weights?.length ? font.weights : [400];
    const min = Math.min(...ws);
    const max = Math.max(...ws);
    return { pkg, kind: 'var', file, weight: min === max ? String(min) : `${min} ${max}` };
  }
  // static: collect the common UI weights that actually ship as files
  let weights = STATIC_WEIGHTS.filter((w) =>
    files.includes(`${font.slug}-latin-${w}-normal.woff2`),
  );
  if (weights.length === 0) {
    const any = (font.weights || []).find((w) =>
      files.includes(`${font.slug}-latin-${w}-normal.woff2`),
    );
    weights = any ? [any] : [];
  }
  if (weights.length === 0) throw new Error(`no static latin woff2 for ${pkg}`);
  return {
    pkg,
    kind: 'static',
    srcs: weights.map((w) => ({ w, file: `${font.slug}-latin-${w}-normal.woff2` })),
  };
}

function declList(font, varName, cssVar) {
  const r = font._resolved;
  const p = (file) => `../../node_modules/${r.pkg}/files/${file}`;
  // preload:false is REQUIRED here. This registry declares ~97 fonts × 2 slots, but a
  // page only ever applies the ONE selected body + heading font (via .variable on
  // <html>). next/font defaults preload:true, which would emit a <link rel="preload">
  // for EVERY declared font — so every page fetched all ~97 woff2 files up front. With
  // preload:false the @font-face rules are still generated, but a font's woff2 is only
  // fetched when it's actually applied — i.e. just the admin-selected (or default)
  // header/body fonts. display:'swap' covers the brief fallback while it loads.
  if (r.kind === 'var') {
    return `const ${varName} = localFont({ src: '${p(r.file)}', weight: '${r.weight}', display: 'swap', preload: false, variable: '${cssVar}' });`;
  }
  const items = r.srcs
    .map((s) => `{ path: '${p(s.file)}', weight: '${s.w}', style: 'normal' }`)
    .join(', ');
  return `const ${varName} = localFont({ src: [${items}], display: 'swap', preload: false, variable: '${cssVar}' });`;
}

// resolve all first (so a missing package fails loudly before writing)
for (const f of LIST) f._resolved = resolveFont(f);

const bodyDecls = LIST.map((f) => declList(f, `${camel(f.slug)}Body`, '--font-inter'));
const headDecls = LIST.map((f) => declList(f, `${camel(f.slug)}Head`, '--font-inter-tight'));

const sansMap = LIST.map((f) => `  ${JSON.stringify(f.key)}: ${camel(f.slug)}Body,`).join('\n');
const displayMap = LIST.map((f) => `  ${JSON.stringify(f.key)}: ${camel(f.slug)}Head,`).join('\n');
const options = LIST.map(
  (f) => `  { value: ${JSON.stringify(f.key)}, label: ${JSON.stringify(f.label + (CAT_SUFFIX[f.category] || ''))} },`,
).join('\n');

const out = `// AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit by hand.
// Self-hosted registry of ~${LIST.length} popular Google fonts (vendored via
// @fontsource[-variable], loaded with next/font/local so the BUILD never fetches
// Google Fonts). Every font is offered for BOTH the body and heading, so the two
// admin selects show the SAME list. Each font is declared twice: once for the
// body slot (variable: --font-inter → globals.css maps to --font-sans) and once
// for the heading slot (variable: --font-inter-tight → --font-display, .ns-theme).
// All are declared preload:false: a page applies only the selected body + heading
// font, so only those woff2 files are fetched (not the whole ~${LIST.length}-font registry).
//
// To change the list: edit scripts/fonts-list.json, run \`pnpm add\` for any new
// packages in apps/{admin,web,widget}, then \`node scripts/gen-fonts.mjs\`.
// This file is identical across apps/{admin,web,widget}/src/app/fonts.ts.
import localFont from 'next/font/local';

// ============================ Body slot (--font-inter) ============================
${bodyDecls.join('\n')}

// ========================== Heading slot (--font-inter-tight) ==========================
${headDecls.join('\n')}

// Same keys in both maps → the body and heading selects offer the same fonts.
export const SANS_FONTS = {
${sansMap}
} as const;

export const DISPLAY_FONTS = {
${displayMap}
} as const;

export type SansKey = keyof typeof SANS_FONTS;
export type DisplayKey = keyof typeof DISPLAY_FONTS;

export const DEFAULT_SANS: SansKey = 'inter';
export const DEFAULT_DISPLAY: DisplayKey = 'inter-tight';

export function sansFont(key?: string | null) {
  return SANS_FONTS[(key as SansKey)] ?? SANS_FONTS[DEFAULT_SANS];
}
export function displayFont(key?: string | null) {
  return DISPLAY_FONTS[(key as DisplayKey)] ?? DISPLAY_FONTS[DEFAULT_DISPLAY];
}

// Body and heading offer the SAME options (popular Google fonts). Category is
// noted in the label so serif/mono/display/handwriting fonts are recognisable.
export const FONT_OPTIONS: { value: SansKey; label: string }[] = [
${options}
];
export const SANS_OPTIONS = FONT_OPTIONS;
export const DISPLAY_OPTIONS: { value: DisplayKey; label: string }[] = FONT_OPTIONS;
`;

for (const app of ['apps/admin', 'apps/web', 'apps/widget']) {
  const dest = path.join(ROOT, app, 'src/app/fonts.ts');
  fs.writeFileSync(dest, out);
  console.log('wrote', dest);
}

// API font-keys list (Zod enum source) — keep in sync with the registry keys.
const keys = LIST.map((f) => `  ${JSON.stringify(f.key)},`).join('\n');
const apiOut = `// AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit by hand.
// Curated font keys; mirror of apps/web/src/app/fonts.ts FONT_OPTIONS values.
// Body and heading accept the SAME keys.
export const FONT_KEYS = [
${keys}
] as const;
export type FontKey = (typeof FONT_KEYS)[number];
`;
const apiDest = path.join(ROOT, 'apps/api/src/lib/font-keys.ts');
fs.mkdirSync(path.dirname(apiDest), { recursive: true });
fs.writeFileSync(apiDest, apiOut);
console.log('wrote', apiDest);

console.log(`\ndone: ${LIST.length} fonts × 2 slots`);
