"use client";

// Quick-reply suggestions for the operator inbox. Fetches three short replies
// generated by the API's /conversations/:id/suggestions endpoint and renders
// them as click-to-insert chips.
//
// Wiring contract: clicking a chip dispatches a `csb:insert-suggestion` window
// CustomEvent whose `detail.text` is the chip's text. The existing Composer in
// inbox-thread.tsx is expected to subscribe to this event and append the text
// into its textarea draft. We do NOT modify the Composer here — there is a
// one-line listener that the inbox owner can add when wiring this panel in.
//
// TODO (composer): in inbox-thread.tsx, add inside the operator-only block:
//   useEffect(() => {
//     const onInsert = (e: Event) => {
//       const detail = (e as CustomEvent<{ text: string }>).detail;
//       setDraft((d) => (d ? `${d.trim()} ${detail.text}` : detail.text));
//     };
//     window.addEventListener("csb:insert-suggestion", onInsert);
//     return () => window.removeEventListener("csb:insert-suggestion", onInsert);
//   }, []);

import { useEffect, useState } from "react";
import { Sparkles, RefreshCw } from "lucide-react";
import { Button } from "@csb/ui";
import { clientApi, ApiError } from "@/lib/api";

type Props = {
  conversationId: string;
};

type SuggestionsResponse = { suggestions: string[] };

export function SuggestionsPanel({ conversationId }: Props) {
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      const res = await clientApi.get<SuggestionsResponse>(
        `/conversations/${conversationId}/suggestions`,
      );
      setSuggestions(Array.isArray(res.suggestions) ? res.suggestions.slice(0, 3) : []);
    } catch (e) {
      setError(e instanceof ApiError ? e.message : (e as Error).message);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      setError(null);
      try {
        const res = await clientApi.get<SuggestionsResponse>(
          `/conversations/${conversationId}/suggestions`,
        );
        if (cancelled) return;
        setSuggestions(Array.isArray(res.suggestions) ? res.suggestions.slice(0, 3) : []);
      } catch (e) {
        if (cancelled) return;
        setError(e instanceof ApiError ? e.message : (e as Error).message);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [conversationId]);

  function pick(text: string) {
    if (typeof window === "undefined") return;
    window.dispatchEvent(
      new CustomEvent("csb:insert-suggestion", { detail: { text } }),
    );
  }

  return (
    <div className="rounded-xl border border-border bg-card p-4">
      <div className="flex items-center justify-between">
        <div className="inline-flex items-center gap-1.5 text-xs font-semibold">
          <Sparkles className="h-3.5 w-3.5 text-primary" />
          Suggestions
        </div>
        <Button
          size="sm"
          variant="ghost"
          onClick={load}
          disabled={loading}
          className="h-6 gap-1 px-2 text-[11px]"
        >
          <RefreshCw className={`h-3 w-3 ${loading ? "animate-spin" : ""}`} />
          Refresh
        </Button>
      </div>

      {error ? (
        <div className="mt-3 rounded-md border border-destructive/40 bg-destructive/5 p-2 text-[11px] text-destructive">
          {error}
        </div>
      ) : null}

      <div className="mt-3 flex flex-col gap-1.5">
        {loading && suggestions.length === 0
          ? Array.from({ length: 3 }).map((_, i) => (
              <div
                key={i}
                className="h-7 animate-pulse rounded-md bg-muted"
              />
            ))
          : suggestions.map((s, i) => (
              <button
                key={`${i}-${s}`}
                type="button"
                onClick={() => pick(s)}
                className="text-left rounded-md border border-border bg-background px-2.5 py-1.5 text-[12px] leading-snug transition hover:border-foreground/40 hover:bg-muted/40"
              >
                {s}
              </button>
            ))}
        {!loading && suggestions.length === 0 && !error ? (
          <div className="text-[11px] italic text-muted-foreground">
            No suggestions available yet.
          </div>
        ) : null}
      </div>
    </div>
  );
}
