import type { Metadata } from 'next';
import { LandingPageShell } from '@/components/ns/landing-page-shell';
import { APP_NAME, APP_LEGAL_NAME } from '@/lib/app-config';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: `Terms of service for ${APP_NAME}.`,
};

export default function Page() {
  return (
    <LandingPageShell>
      <section className="main-container px-5 py-20 lg:py-28">
        <div className="mx-auto max-w-3xl">
          <h1 className="font-display text-4xl font-bold tracking-tight text-primary mb-2">Terms of Service</h1>
          <p className="text-primary-50 mb-10">Last updated: December 26, 2025</p>

          <div className="prose prose-invert max-w-none space-y-8 text-primary-50">

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using {APP_NAME} (&ldquo;Service&rdquo;), operated by {APP_LEGAL_NAME}, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.</p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">2. Description of Service</h2>
              <p>{APP_LEGAL_NAME} provides {APP_NAME}, an AI-powered customer support platform including live chat, automated responses, knowledge base management, and related tools. We reserve the right to modify, suspend, or discontinue any part of the Service at any time.</p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">3. Nature of Service (Automated Software)</h2>
              <p className="mb-2">{APP_NAME} is a fully automated software-as-a-service (SaaS) platform. Our Service:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Is entirely software-based and automated</li>
                <li>Does not involve any human-driven services, manual labor, or consulting</li>
                <li>Provides instant, automated analysis and responses generated by our algorithms</li>
                <li>Operates without human intervention in delivering core functionality</li>
                <li>Uses AI and machine learning for automated recommendations and insights</li>
              </ul>
              <p className="mt-2">All features are delivered through automated systems without any manual human processing of your data or requests.</p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">4. User Accounts</h2>
              <ul className="list-disc pl-6 space-y-1">
                <li>You must provide accurate and complete registration information</li>
                <li>You are responsible for maintaining the security of your account</li>
                <li>You must notify us immediately of any unauthorized access</li>
                <li>You may not share your account credentials with others</li>
                <li>One person or entity may not maintain multiple free accounts</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">5. Subscription and Payment</h2>
              <ul className="list-disc pl-6 space-y-1">
                <li>Paid subscriptions are billed in advance on a monthly or annual basis</li>
                <li>All fees are non-refundable except as stated in our Refund Policy</li>
                <li>We may change pricing with 30 days notice to existing subscribers</li>
                <li>You authorize us to charge your payment method for recurring fees</li>
                <li>Failure to pay may result in suspension or termination of your account</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">6. Acceptable Use</h2>
              <p className="mb-2">You agree not to:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Use the Service for any illegal or unauthorized purpose</li>
                <li>Attempt to gain unauthorized access to our systems</li>
                <li>Interfere with or disrupt the Service or servers</li>
                <li>Scrape, crawl, or spider any part of the Service without permission</li>
                <li>Use the Service to harm, threaten, or harass others</li>
                <li>Resell or redistribute the Service without authorization</li>
                <li>Use automated tools to access the Service beyond normal usage</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">7. Intellectual Property</h2>
              <p>The Service and its original content, features, and functionality are owned by {APP_LEGAL_NAME} and are protected by international copyright, trademark, and other intellectual property laws. You retain ownership of any data you submit to the Service.</p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">8. Data and Privacy</h2>
              <p>Your use of the Service is also governed by our <a href="/privacy" className="text-primary underline underline-offset-2">Privacy Policy</a>. By using the Service, you consent to the collection and use of information as described in our Privacy Policy.</p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">9. Disclaimer of Warranties</h2>
              <p>THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND. The company does not guarantee uninterrupted, secure, or error-free operation. Results may vary considerably.</p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">10. Limitation of Liability</h2>
              <p>{APP_LEGAL_NAME.toUpperCase()} SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES to the maximum extent permitted by law.</p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">11. Termination</h2>
              <p>We may terminate or suspend your account at any time for violations of these Terms. Upon termination, your right to use the Service will immediately cease. You may cancel your account at any time through your account settings.</p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">12. Changes to Terms</h2>
              <p>We reserve the right to modify these Terms at any time. We will notify users of material changes via email or through the Service. Continued use after changes constitutes acceptance.</p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-primary mb-3">13. Contact Us</h2>
              <p>Email: <a href={`mailto:legal@${APP_NAME.toLowerCase()}.app`} className="text-primary underline underline-offset-2">legal@{APP_NAME.toLowerCase()}.app</a></p>
            </div>

          </div>
        </div>
      </section>
    </LandingPageShell>
  );
}
